settings:
  min-players: 2

cases:
  tania_skrzynka:
    display-name: "&aTania Skrzynka"
    cost: 5
    items:
      - material: "DIAMOND"
        amount: 1
        chance: 40.0
      - material: "IRON_INGOT"
        amount: 5
        chance: 60.0
  droga_skrzynka:
    display-name: "&cDroga Skrzynka"
    cost: 15
    items:
      - material: "NETHERITE_INGOT"
        amount: 1
        chance: 40.0
      - material: "DIAMOND"
        amount: 1
        chance: 60.0
