settings:
  min-players: 2
  max-players: 4

cases:
  tania_skrzynka:
    display-name: "&aTania Skrzynka"
    cost: 5
    items:
      - material: DIAMOND
        amount: 3
        chance: 10.0
        display-name: "&bDiamenty x3"
      - material: IRON_INGOT
        amount: 5
        chance: 90.0
        display-name: "&fŻelazo x5"

  droga_skrzynka:
    display-name: "&6Złota Skrzynka"
    cost: 16
    items:
      - material: NETHERITE_INGOT
        amount: 1
        chance: 10.0
        display-name: "&dSztabka Netheritu"
      - material: GOLD_INGOT
        amount: 10
        chance: 90.0
        display-name: "&eZłoto x10"
